# Starter pipeline
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      C:\SoftwareAG\common\AssetBuildEnvironment\bin\build.bat