trigger:
  branches:
    include:
      - master  # or your desired branch

pool:
  name: self_hosted_pool

steps:
- checkout: self
- task: PowerShell@2
  displayName: 'Build webMethods package using ABE'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Building webMethods package..."
      C:\SoftwareAG\common\AssetBuildEnvironment\bin\build.bat
- task: PowerShell@2
  displayName: 'Prepare deployment files using Deployer'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Prepare deployment files..."
      C:\SoftwareAG\IntegrationServer\instances\default\packages\WmDeployer\bin\projectautomator.bat ProjectAutomator.xml