# Starter pipeline
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      #Write-Host "Hello World"
      C:\SoftwareAG\common\AssetBuildEnvironment\bin\build.bat